/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const RegisterLazyRouteImport = createFileRoute('/register')()
const LoginLazyRouteImport = createFileRoute('/login')()
const DrawChar123drawIdChar125LazyRouteImport =
  createFileRoute('/draw/{$drawId}')()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawChar123drawIdChar125LazyRoute =
  DrawChar123drawIdChar125LazyRouteImport.update({
    id: '/draw/{$drawId}',
    path: '/draw/{$drawId}',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/draw/{$drawId}.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/draw/{$drawId}': typeof DrawChar123drawIdChar125LazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/draw/{$drawId}': typeof DrawChar123drawIdChar125LazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/draw/{$drawId}': typeof DrawChar123drawIdChar125LazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/draw/{$drawId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/draw/{$drawId}'
  id: '__root__' | '/' | '/login' | '/register' | '/draw/{$drawId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  DrawChar123drawIdChar125LazyRoute: typeof DrawChar123drawIdChar125LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw/{$drawId}': {
      id: '/draw/{$drawId}'
      path: '/draw/{$drawId}'
      fullPath: '/draw/{$drawId}'
      preLoaderRoute: typeof DrawChar123drawIdChar125LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginLazyRoute: LoginLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  DrawChar123drawIdChar125LazyRoute: DrawChar123drawIdChar125LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
